set windows-shell := ["pwsh.exe", "-nop", "-c"]

api-json:
    RoboSAPiens\lib\RoboSAPiens.exe --export-api ((pwd).path + "\api.json")

localize-en: api-json
    #!powershell
    python schemagen.py api.json
    mypy localized/en.py

localize-i18n: localize-en
    #!powershell
    python schemagen.py api.json i18n
    rm api.json
    mypy localized/

libgen: localize-i18n
    python libgen.py

mypy:
    mypy RoboSAPiens

build: libgen mypy
