set windows-shell := ["pwsh.exe", "-NoProfile", "-Command"]

localize-en:
    python schemagen.py api.json
    mypy localized/en.py

localize-i18n: localize-en
    python schemagen.py api.json i18n
    rm api.json
    mypy localized/

libgen: localize-i18n
    python libgen.py

mypy:
    mypy RoboSAPiens

build: libgen mypy
