<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SAPFEWSELib">
      <HintPath>lib/sapfewse.dll</HintPath>
      <SpecificVersion>False</SpecificVersion> 
    </Reference>
    <Reference Include="SAPROTWR.NET">
      <HintPath>lib/saprotwr.net.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="bootstrap\*">
      <TargetPath>bootstrap\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetJinja" Version="1.0.4" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.PersistentFile" Version="4.2.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>
</Project>
