set windows-shell := ["pwsh.exe", "-NoProfile", "-Command"]

python-requirements:
    pip install -r requirements.txt

gen-robosapiens: python-requirements
    Get-Content ../VERSION | Join-String -FormatString "__version__ = '{0}'" | Set-Content src/version.py
    cd src; just build

build-wheel: gen-robosapiens
    python -m build --wheel

gendoc:
    libdoc -P .\src RoboSAPiens ../docs/RoboSAPiens.html
    libdoc -P .\src RoboSAPiens.DE ../docs/RoboSAPiens.DE.html
    python localizedoc.py ../docs/RoboSAPiens.DE.html

clean:
    if (Test-Path build) { rm -r build }
    if (Test-Path dist) { rm -r dist }
    cd src; just clean

build: build-wheel gendoc
